services:

  mysql:
    container_name: mysql
    restart: always
    image: 'mysql/mysql-server:8.0'
    environment:
          MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ROOT_HOST: '%'
          MYSQL_DATABASE: '${DB_DATABASE}'
          MYSQL_USER: '${DB_USERNAME}'
          MYSQL_PASSWORD: '${DB_PASSWORD}'
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - '${FORWARD_DB_PORT:-3307}:3306'
    volumes:
      - mysql_local:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
      retries: 3
      timeout: 5s

  node_web_backend:
    container_name: node_web_backend
    restart: always
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      # - '${BACKEND_PORT:-5000}:5000'
      - '${DEBUG_BACKEND_PORT:-9229}:9229'
    environment:
      - NODE_ENV=${APP_ENV}
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    ports:
      - '80:80'
      - '443:443'
      # - "8000:80"
      # - "8001:443"
    depends_on:
      - node_web_backend
    volumes:
      - /etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - /etc/letsencrypt:/etc/letsencrypt
      - ./docker/nginx/webroot:/usr/src/app
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf


volumes:
  mysql_local:
    driver: local
